on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install AutoHotkey v1
        shell: pwsh
        run: |
          $path = (Get-Item .).FullName + "\src\Installer\_scripts";
          Write-Output "Path: $path";
          Invoke-WebRequest "https://www.autohotkey.com/download/1.1/AutoHotkey_1.1.37.02.zip" -OutFile "$path\autohotkey.zip";
          Expand-Archive -Path "$path\autohotkey.zip" -DestinationPath "$path\_autohotkey\" -Force;
          Remove-Item -Path "$path\autohotkey.zip" -Force;

      - uses: nuget/setup-nuget@v2
      - run: nuget restore .\src\Installer\SwitchApps.sln

      - name: Build the dependencies and the installers
        shell: pwsh
        run: |
          .\src\Installer\_scripts\build_all_installers.ps1

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: src/Installer/_build/SwitchApps*
          file_glob: true
          draft: true
          release_name: draft